trigger:
  - master

variables: 
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]

resources:
  repositories:
    - repository: templates
      type: github
      name: Justin-DynamicD/azure_pipeline-templates
      endpoint: GitHub

jobs:
  - template: powershell_module.yml@templates
    parameters:
      module_name: adfs-management
      module_version: $(majorMinorVersion).$(semanticVersion)
